In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
print("All library imported successfully")

All library imported successfully


In [2]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.random.rand(3,2)

array([[0.84879894, 0.20777974],
       [0.90247957, 0.80400685],
       [0.11236318, 0.76614335]])

In [9]:
np.random.randn(3,2)

array([[-0.63418221,  0.60017894],
       [ 1.20412935,  0.49791029],
       [ 1.02013699, -1.59520378]])

In [11]:
Array Attributes

In [12]:
arr=np.array([[1,2,3], [4,5,6]])

In [13]:
print(arr.shape)

(2, 3)


In [14]:
print(arr.ndim)

2


In [15]:
print(arr.size)

6


In [16]:
print(arr.dtype)


int64


In [ ]:
Array Operations

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [18]:
a+b

array([5, 7, 9])

In [19]:
a*b

array([ 4, 10, 18])

In [20]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [21]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [22]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
Aggregration

In [23]:
arr=np.array([1,2,3,4])

In [24]:
arr.sum()

np.int64(10)

In [25]:
arr.mean()

np.float64(2.5)

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.std()

np.float64(1.118033988749895)

In [ ]:
Indexing and slicing

In [28]:
arr=np.array([1,2,3,4,5])

In [29]:
arr[0]

np.int64(1)

In [30]:
arr[1:4]

array([2, 3, 4])

In [31]:
arr=np.array([[1,2,3],[4,5,6]])

In [32]:
arr[0,1]

np.int64(2)

In [33]:
arr = np.array([1, 2, 3, 4, 5])

In [34]:
mask=arr>3

In [35]:
arr[mask]

array([4, 5])

In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(mask)
print(arr[mask])

[False False False  True  True]
[4 5]


In [ ]:
Reshaping  and Combining Arrays

In [37]:
arr = np.arange(6)

In [38]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
a = np.array([1, 2])
b = np.array([3, 4])

In [40]:
np.concatenate((a, b))

array([1, 2, 3, 4])

In [41]:
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [42]:
np.hstack((a, b))

array([1, 2, 3, 4])

In [ ]:
Broadcasting

In [43]:
a = np.array([1, 2, 3])

In [44]:
a+5

array([6, 7, 8])

In [ ]:
Saving and Loading Arrays

In [45]:
np.save('array.npy',arr)

In [46]:
loaded_arr=np.load('array.npy')